config/routes.rb
R20130214Cookbook::Application.routes.draw do
  resources :books, :recipes, :ingredients
end

app/models/book.rb
class Book < ActiveRecord::Base
 attr_accessible :title, :cuisine, :chef, :image, :recipe_ids
 has_many :recipes
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  attr_accessible :name, :measurement, :cost, :image
  has_and_belongs_to_many :recipes
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  attr_accessible :name, :course, :cooktime, :servingsize, :instructions, :image
  belongs_to :book
  has_and_belongs_to_many :ingredients
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end
  def new
    @book = Book.new
  end
  def create
    book = Book.create(params[:book])
    redirect_to(book)
  end
  def show
    @book = Book.find(params[:id])
  end
  def edit
    @book = Book.find(params[:id])
  end
  def update
    book = Book.find(params[:id])
    book.update_attributes(params[:book])
    redirect_to(book)
  end
  def destroy
    book = Book.find(params[:id])
    book.delete
    redirect_to(book)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.all
  end
  def new
    @ingredient = Ingredient.new
  end
  def create
    ingredient = Ingredient.create(params[:ingredient])
    redirect_to(ingredient)
  end
  def show
    @ingredient = Ingredient.find(params[:id])
  end
  def edit
    @ingredient = Ingredient.find(params[:id])
  end
  def update
    ingredient = Ingredient.find(params[:id])
    ingredient.update_attributes(params[:ingredient])
    redirect_to(ingredient)
  end
  def destroy
    ingredient = Ingredient.find(params[:id])
    ingredient.delete
    redirect_to(ingredients)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end
  def new
    @recipe = Recipe.new
  end
  def create
    recipe = Recipe.create(params[:recipe])
  end
  def show
    @recipe = Recipe.find(params[:id])
  end
  def edit
    @recipe = Recipe.find(params[:id])
  end
  def update
    recipe = Recipe.find(params[:id])
    recipe.update_attributes(params[:recipe])
    redirect_to(recipe_path)
  end
  def destroy
    recipe = Recipe.find(params[:id])
    recipe.delete
    redirect_to(recipes)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_form.html.erb
<%= form_for @book do |f| %>

<%= f.label :title, "Book Title", :autofocus => 'autofocus' %>
<%= f.text_field :title %>
<%= f.label :cuisine %>
<%= f.text_field :cuisine %>
<%= f.label :chef %>
<%= f.text_field :chef %>
<%= f.label :image %>
<%= f.text_field :image %>
<br>
<% Recipe.all.each do |recipe| %>
  <span><%= recipe.name %></span>
  <%= check_box_tag 'book[recipe_ids][]', recipe.id, recipe.in?(@book.recipes.to_a) %>
<% end %>
<br>
<%= f.submit %>
<% end %>

app/views/books/edit.html.erb
<h1>Edit Book</h1>
<%= render :partial => 'form' %>

app/views/books/index.html.erb
<nav class='small-nav'><%= link_to 'Add Book', new_book_path %></nav>
<div class='book-section'>
  <ol>
    <% @books.each do |book| %>
      <li>
        <ul>
          <%= image_tag(book.image) %>
          <li id='li-title'><%= link_to(book.title, book) %></li>
          <br>
          <li><%= book.cuisine %></li>
          <br>
          <li><%= book.chef %></li>
          <br>

        </ul>
      </li>
    <% end %>
  <ol>
</div>

app/views/books/new.html.erb
<h1>New Book</h1>
<%= render :partial => 'form' %>

app/views/books/show.html.erb
<div class='book-section'>
  <%= image_tag(@book.image) %>
  <%= link_to 'Edit', edit_book_path(@book) %>
  <%= link_to 'Delete', book_path(@book), :method => :delete, :confirm => 'Are you sure you want to delete?' %>
  <li id='li-title2'><%= link_to(@book.title, @book) %></li>
  <li><%= @book.cuisine %></li>
  <li><%= @book.chef %></li>
</div>

app/views/ingredients/show.html.erb
<div class='book-section'>
  <%= image_tag(@ingredient.image) %>
  <li><%= @ingredient.name %></li>
  <li><%= @ingredient.chef %></li>
</div>
<div class='recipe-section'>
  <% @ingredient.recipes.each do |recipe| %>
  <li><%= recipe.name %></li>
  <li><%= image_tag(ingredient.image) %></li>
      <li><% recipe.ingredients.each do |ingredient| %></li>
      <li><%= ingredient.name %></li>
      <%= image_tag(ingredient.image) %>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>R20130214Cookbook</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>
    <%= link_to 'Books', books_path %>
    <br>
    <%= link_to 'Recipes', recipes_path %>

  </nav>

<%= yield %>

</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>

<%= f.label :name, "Recipe Name", :autofocus => 'autofocus' %>
<%= f.text_field :name %>
<%= f.label :course %>
<%= f.text_field :course %>
<%= f.label :servingsize, 'Serving Size' %>
<%= f.text_field :servingsize %>
<%= f.label :instructions %>
<%= f.text_field :instructions %>
<%= f.label :image %>
<%= f.text_field :image %>
<br>
<% Ingredient.all.each do |ingredient| %>
  <span><%= ingredient.name %></span>
  <%= check_box_tag 'recipe[ingredient_ids][]', ingredient.id, ingredient.in?(@recipe.ingredients.to_a) %>
<% end %>
<br>
<%= f.submit %>
<% end %>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>
<%= render :partial => 'form' %>

app/views/recipes/index.html.erb
<nav class='small-nav'><%= link_to 'Add Recipe', new_recipe_path %></nav>

  <% @recipes.each do |recipe| %>
  <div class='recipe-section'>
    <ul>
      <%= image_tag(recipe.image) %>
      <li id='li-title'><%= recipe.name %></li>
      <br>
      <li><%= recipe.course %></li>
      <br>
      <li><%= recipe.servingsize %></li>
    </ul>
    <%= link_to 'Edit', edit_recipe_path(recipe.id) %>
    <%= link_to 'Delete', @recipe, :method => :delete, :confirm => 'Are you sure you want to delete?' %>
  </div>
    <% end %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>
<%= render :partial => 'form' %>

app/views/recipes/show.html.erb
<div class='recipe-section'>
  <%= image_tag(@recipe.image) %>

  <li id='li-title2'><%= @recipe.name %></li>
  <li><%= @recipe.course %></li>
  <li><%= @recipe.servingsize %></li>
  <li><%= @recipe.instructions %></li>
</div>